name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: TypeScript Build
        uses: alexthemaster/action-build-typescript@v1.3.1
